
language: node_js

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

node_js:
  - node
  - 6
  - 4

services:
  - docker

before_script:
  - docker build -t kdc:test .
  - docker run -d -p 127.0.0.1:88:88/udp -p 127.0.0.1:8000:8000 --name docker-kdc kdc:test
  - sudo apt-get install -qq -y krb5-user krb5-config
  - sudo cp ./tests/kerberos/krb5.conf /etc/krb5.conf

after_script:
  - npm run test-cov
  - npm run test-integration
  - docker kill $(docker ps -q)
  - codecov
  - cat ./coverage/lcov.info | coveralls

webhooks:
  urls: https://webhooks.gitter.im/e/237280ed4796c19cc626
  on_success: change  # options: [always|never|change] default: always
  on_failure: always  # options: [always|never|change] default: always
  on_start: false     # default: false

sudo: required
